### PR TITLE
Fix SEO metadata and general readability

### LINKED ISSUE #3: Use OpenGraph and Twitter Cards for SEO and mobile immersion
if you include certain properties in the head, Facebook displays a nice picture instead of a gray box. See here for an example. 

https://github.com/Z1MM32M4N/blog/blob/master/source/_includes/head.html#L39-#65

Really any image would work. Your best bet would be to just take a screenshot of the homepage or use the tartanhacks logo on a red background.

### PR DESCRIPTION
**Pull request by jez**
## Commit Summary

e7292fe
   Updated SEO and social media meta data. Closes #3

bfe5a81
   Rework event information
- Changed "Registration" to "About" and moved paragraph information
  there
  - Improves readability of text (background is static rather than
    moving)
- Corrected spelling of "ScottyLabs" from "Scottylabs"
- Increased size of date information in landing page

7ddcf17
   Use small caps for readability

   The central TartanHacks logo is hard to read because this font doesn't
   space out all caps enough. Rather than adjusting the kerning, use small
   caps to improve readability.

### CODE REVIEW

**Comment by jez** [comment]
You can see it live at http://www.zimmerman.io/tartanhacks/

**Comment by tomshen** [comment]
The first section should fill the window:
screen shot 2015-01-16 at 10 34 11 pm

There shouldn't be that white bar at the bottom. This is an issue on the current version of the site too.

I think the FAQ section would look better without the Qs and As.

**Comment by jez** [comment]
I was actually looking into making the whole "splash" section fill the viewport, similar to the way that https://zimmerman.io does it. I was running into mobile responsiveness issues. To be fair, the "bar" isn't there purposefully. The size of the splash section is determined solely by the size of the components; it isn't being sized according to a height in pixels or percentages.

**Comment by jez** [comment]
@tomshen I fixed up the splash image and changed the Q's and A's. The changes should be live at http://www.zimmerman.io/tartanhacks/

**Comment by tomshen** [comment]
:ship:

**Comment by bezi** [comment]
There is a reason I didn't make it full screen.  It makes it really
annoying to fill in forms on android because the location jumps all over
the place when the viewport sizing changes.  It also makes it jittery on
scroll.  % heights = problems for mobile

**Comment by jez** [comment]
> So, as noted on the comments, I explicitly didn't make the height 100% of the viewport because it changes a lot in android.  When I scroll, when I pull up the keyboard, it really freaks out

I'm looking at your site on a Nexus 5 right now. I can scroll just fine, with no problems pulling up a keyboard.

> And even though Apple is master race, there are a good number of people using Android.  Also, I'm of the opinion that having the 100% height doesn't make it clear that there's more below, as scrollbars are becoming very small in browsers and are nonexistent in mobile

Scroll bars becoming small to non-existent is because modern users are getting used to the idea of scrolling to consume content. People rarely see a full splash page and don't scroll. Take for example Medium, which uses beautiful, 100% cover images as titles for each post. This is a conscious decision that improves our design by partaking in modern principles.

There are no forms on this page, so I'm not sure why you mentioned them breaking. Also, percentage heights are actually one of the best ways to make a site mobile responsive.

**Comment by tomshen** [comment]
Having a splash image that takes up less than the full height looks really bad. If the issue is that people don't know to scroll, we can add a little downward arrow at the bottom of the splash image.

**Comment by bezi** [comment]
There are indeed several forms on the page that will be pushed.  Registration, ResumeDrop, the admin panel, and team management are all annoying.  Percent widths and media queries help with responsiveness, and I'm reporting the bug from my own Nexus 5 running the latest Chrome.  Go down, then up.  Notice how the content shifts up and down because the address bar pops up when you move up, changing the viewport height, resizing the splash, and shoving the content up about 30 pixels.  It's even more dramatic when the keyboard is pulled up to say, fill in a form, which is a very legitimate use case of this website in the very near future.

I disagree with the splash image not taking up the full height looking good.  It is a splash logo, and then there is content.  It makes perfect sense to me that it take up a certain amount of space, namely the amount of space that the logo calls for.

**Comment by jez** [comment]
Forms for those sort of purposes should be placed on their own page, for example tartanhacks.com/register/

I acknowledge the address bar hiding, though if you simply move the forms to it's own page that doesn't have a 100% splash image, this will be a non issue. Additionally, separating content into logical pages helps with linking to the page, SEO, and general usability.

**Comment by tomshen** [comment]
We should have links to those other pages on the top right. The splash should only be on the main page. It should convert to a sticky header when you scroll down on the main page, and should be replaced with a normal header on other pages.

**Comment by bezi** [comment]
This is incredibly overkill.  A single-page app fulfills our needs admirably.   Why are we considering SEO for a website that will be up for less than two weeks, has a captive audience in our hackers, and worked just fine before we started futzing around with the CSS?  Not to say that on their own these changes aren't fine, but I am working with the context of the person who wrote all the other code that needs to go live soon, and the needs thereof.  Furthermore, my time is not infinite.  The website that I'm proposing is a single-page app by the necessity of my sanity and the many other demands on my time.

Best practices are good, shipping a working product is more important given our constraints.  Part of that is being able to use a form.  Linking isn't an issue because ID's are a thing.  SEO is not a problem because we don't actually care about how well we show up on a search engine, I guarantee you that we are and will remain the top result when searching for 'TartanHacks' or 'CMU hackathon'.  So can we please just make this website I've spent more time that I should have on at least work on my own device.

**Comment by jez** [comment]
The TartanHacks website is the page that everyone will see. It is the most front facing part of TartanHacks. In addition to serving the needs of the hackers, sponsors and outsiders will see this site. Anyone who wants to know anything about what TartanHacks is will see this site.

The splash is the first thing that hackers and sponsors see, and having it look stunning is important. Making it take up the whole page accomplishes this. It not only needs to serve the utilitarian functions you mention, but it has to shock and awe. As an organization, we have a reputation to uphold, and this site is one step along the path to ensuring that we do.

Most of the styles will be able to share the same main.css file. What changes you've made (which you can get by checking the git diff) you can simply include in a separate CSS file to be included on the separate registration page. This should take minimal effort with copying and pasting.

The benefits of ensuring that out home page is uncluttered and well-designed outweigh the costs of refactoring the site into two small pages.

**Comment by bezi** [comment]
You know what, you're completely correct and I apologize for getting in the way of progress.  I'll return to writing the app, and then will spend extra time to make sure that it is in _two_ nice pages, just for you.  Thank you for pointing out the error in my ways, and I'll make sure not to repeat them.

**Comment by tomshen** [comment]
Oscar, thank you for taking the time to work on the app. Ultimately, if the styling interferes with functionality, then functionality definitely comes first. So make what changes you need to to get to a working app. Also, you probably don't need to finish it right now. As long as we have something working by Monday it'll be fine.

Jake, I agree that a good main page is important, but we need to prioritize working registration first. Once there exists a version of the site with working registration, we can iterate on style.

**Pull request merged**
